version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.4.2
    environment:
      - "discovery.type=single-node"
    restart: always
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
